
      
    <div class="c-wrapper">
      <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        <div style='    display: flex;
        align-items: center;'>
        
        <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true"><span class="c-header-toggler-icon"></span></button>
        <h2 style='margin-left: 25px;margin-top: 7px'>
          @if(empty(Auth::user()))
          <span></span>
          @else
          {{Auth::user()->name}}
          @endif
        </h2>
      </div>
        <ul class="c-header-nav ml-auto mr-4">

          <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link">
              <!-- Generated by IcoMoon.io -->
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <title>arrow-circle-bottom</title>
          <path d="M12 0.75c-6.213 0-11.25 5.037-11.25 11.25s5.037 11.25 11.25 11.25 11.25-5.037 11.25-11.25-5.037-11.25-11.25-11.25zM18.894 18.894c-1.757 1.752-4.182 2.835-6.859 2.835-5.365 0-9.715-4.349-9.715-9.715s4.349-9.715 9.715-9.715c5.365 0 9.715 4.349 9.715 9.715 0 1.365-0.282 2.664-0.79 3.843l0.024-0.063c-0.517 1.205-1.222 2.234-2.090 3.099l-0 0z"></path>
          <path d="M12.755 14.741v-8.741h-1.5v8.741l-3.518-3.518-1.061 1.061 5.329 5.329 5.329-5.329-1.061-1.061-3.518 3.518z"></path>
          </svg>
          </a></li>
          <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <div class="c-avatar">
                @if(empty(Auth::user()))
                <span></span>
                @elseif(Auth::user()->name=='admin')
                <img class="c-avatar-img" src="/assets/img/avatars/nabil.jpg" alt="user@email.com">
                @else
                <img class="c-avatar-img" src="/assets/img/765-default-avatar.png" alt="user@email.com">
                @endif
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
              <div class="dropdown-header bg-light py-2"><strong>Account</strong></div><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-bell"></use>
                </svg> Updates<span class="badge badge-info ml-auto">2</span></a><a class="dropdown-item" href="#">
                {{-- <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-envelope-open"></use>
                </svg> Messages<span class="badge badge-success ml-auto">2</span></a><a class="dropdown-item" href="#"> --}}
                {{-- <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-task"></use>
                </svg> Tasks<span class="badge badge-danger ml-auto">2</span></a><a class="dropdown-item" href="#"> --}}
                <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-comment-square"></use>
                </svg> Comments<span class="badge badge-warning ml-auto">5</span></a>
              <div class="dropdown-header bg-light py-2"><strong>Settings</strong></div><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-user"></use>
                </svg> Profile</a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-settings"></use>
                </svg> Settings</a><a class="dropdown-item" href="#">
                {{-- <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-credit-card"></use>
                </svg> Payments<span class="badge badge-secondary ml-auto">42</span></a><a class="dropdown-item" href="#"> --}}
                {{-- <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-file"></use>
                </svg> Projects<span class="badge badge-primary ml-auto">42</span></a> --}}
              {{-- <div class="dropdown-divider"></div><a class="dropdown-item" href="#"> --}}
                {{-- <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-lock-locked"></use>
                </svg> Lock Account</a><a class="dropdown-item" href="/login"> --}}
                <svg class="c-icon mr-2">
                  <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-account-logout"></use>
                </svg><form action="/logout" method="POST"> @csrf <button type="submit" class="btn btn-ghost-dark btn-block">Logout</button></form></a>
            </div>
          </li>
        </ul>
        <div class="c-subheader px-3">
          <ol class="breadcrumb border-0 m-0">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php $segments = ''; ?>
            @for($i = 1; $i <= count(Request::segments()); $i++)
                <?php $segments .= '/'. Request::segment($i); ?>
                @if($i < count(Request::segments()))
                    <li class="breadcrumb-item">{{ Request::segment($i) }}</li>
                @else
                    <li class="breadcrumb-item active">{{ Request::segment($i) }}</li>
                @endif
            @endfor
          </ol>
        </div>
    </header>